
name: castnow_app
description: "CastNow Mobile Client - Native P2P Screen Sharing"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 原生 WebRTC 支持 (音视频核心)
  flutter_webrtc: ^0.12.5
  # PeerJS 的 Dart 实现 (与 Web 端互通)
  peerdart: ^0.5.6
  # 权限处理
  permission_handler: ^11.3.1
  # 屏幕常亮
  wakelock_plus: ^1.1.2
  # 唯一 ID 生成
  uuid: ^4.3.3
  url_launcher: ^6.3.2
  shared_preferences: ^2.2.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_source.png"
  adaptive_icon_background: "#020617"
  adaptive_icon_foreground: "assets/icon/bolt_foreground.png"
  min_sdk_android: 21




flutter:
  uses-material-design: true
  assets:
    - assets/icon/

dependency_overrides:
  flutter_webrtc: ^0.12.1